### ISSUE TITLE
[BUG] Genshin Impact Unhandled Error

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#28]
Yet another bug (I am actually thinking of sharing with you my Discord to contact about the issues I'm finding because I'm finding quite a lot of issues recently, and I do apologize for that)

![image](https://user-images.githubusercontent.com/12277635/192652672-b55f9ebf-6628-4829-9eb2-7c15c9ef955c.png)

**Comment by neon-nyan** [comment]
Hi,

No need to worry. Though, thank you for the feedback and the reports to this launcher. It's really useful for me to improve this launcher overtime.

I could say that this issue is related to the outdated Dispatcher key for Genshin, which is still using 3.0. It's not automatic and I have to update it manually. I will update it once I go home (still working in the office here lol)

**Comment by neon-nyan** [comment]
I just updated the Dispatcher key in metadata for Genshin 3.1 update and it should fix this issue.
Please click **Update Metadata** button in the notification to update the metadata.

![image](https://user-images.githubusercontent.com/30566970/192793406-6b851280-74d7-460c-aadc-d24719c93e6d.png)

**Comment by muscularcandy67** [comment]
Can't confirm if it works since I had already updated the game in the meantime

**Comment by neon-nyan** [comment]
Anyway, the method that got bugged before is actually being used in "Repair Game:" feature. You can either try that to confirm if the issue still persist or not.
In my case, the issue itself has already been solved.

**Comment by muscularcandy67** [comment]
In Genshin or in Honkai?

**Comment by neon-nyan** [comment]
I mean, In Genshin.

**Comment by muscularcandy67** [comment]
I don't see the repair function on Genshin Global

**Comment by neon-nyan** [comment]
It's been a while and sorry for my very late reply.
I just noticed that the previous build will be mistakenly remove the Repair Button on Game Settings.
Can you try the latest commit I just pushed? and see if the button is there.

![image](https://user-images.githubusercontent.com/30566970/195123886-422670c6-15c1-4d76-988e-4644a8f661f8.png)

**Comment by muscularcandy67** [comment]
System.Text.Json.JsonException: '0x00' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0x00' is invalid after a single JSON value. Expected end of data. LineNumber: 1 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerContext context)
   at Hi3Helper.Data.GenshinDispatchHelper.LoadDispatchInfo() in F:\myGit\CollapseLauncher\Hi3Helper.Core\Classes\Data\Tools\GenshinDispatchHelper\GenshinDispatchHelper.cs:line 50
   at CollapseLauncher.InstallManagement.InitializeNewGenshinDispatch() in C:\myGit\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 710

**Comment by muscularcandy67** [comment]
When trying to repair Genshin

**Comment by muscularcandy67** [comment]
I compiled the launcher up to 09385dac03dd8d06f6145dbb2f96517feb1965c1 commit and the repair function works without giving me any error, and it's actually downloading extra files, probably those I miss for the time I was off from Genshin

**Comment by neon-nyan** [comment]
Glad to hear that.
If you feel that the issue is now fixed, I think we can close this issue then.

**Comment by muscularcandy67** [comment]
Yup, so I'm going ahead and declare this issue fixed, until we need a new dispatcher key
