### ISSUE TITLE
Error when changing graphic settings from the launcher in Honkai Impact

### ISSUE THREAD

**Issue by aliimran04** [neon-nyan/CollapseLauncher#36]
I am using the latest release candidate version. When I apply graphic settings through the launcher, the game give this type of error. I need to reset the game graphic by deleting some registry .
![BH3_qwOumY8LlP](https://user-images.githubusercontent.com/83760584/196338192-27e3cd50-d102-4f7a-9d19-66de1839c50c.png)

**Comment by aliimran04** [comment]
[1.0.40.9-preview] launcher version doesn't have this error occured.

**Comment by neon-nyan** [comment]
Seems like some JSON values in registry didn't serialized properly since changes from using ``Newtonsoft.Json`` to ``System.Text.Json``

Will investigate this issue further.

**Comment by neon-nyan** [comment]
This issue has been addressed in the latest https://github.com/neon-nyan/CollapseLauncher/commit/69ff12e400f9a3af7de19f0ae4b5b960a0b48489 commit.

You can try download and install this build, then re-apply the Game Settings and launch the game and let's see if this build will fix that.

### Download
https://github.com/neon-nyan/CollapseLauncher/releases/tag/CL-v1.0.52.1-fix20221019-test

**Comment by aliimran04** [comment]
But the cache update feature doesn't work. It gives this error when try to update. 
`System.Net.Http.HttpRequestException: HttpResponse has returned unsuccessful code: BadGateway
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream) in C:\myGit\CollapseLauncher\Hi3Helper.Http\Class\Session\SessionManager.cs:line 47
   at Hi3Helper.Http.Http.<>c__DisplayClass60_0.<Download>b__0() in C:\myGit\CollapseLauncher\Hi3Helper.Http\Http.cs:line 120
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken) in C:\myGit\CollapseLauncher\Hi3Helper.Http\Http.cs:line 119
   at CollapseLauncher.Pages.CachesPage.FetchCachesAPI() in C:\myGit\CollapseLauncher\CollapseLauncher\Classes\CachesManagement\CachesCheck.cs:line 100
   at CollapseLauncher.Pages.CachesPage.DoCachesCheck() in C:\myGit\CollapseLauncher\CollapseLauncher\Classes\CachesManagement\CachesCheck.cs:line 63`

**Comment by aliimran04** [comment]
maybe the same issue like the previous issue i reported?

**Comment by aliimran04** [comment]
https://github.com/neon-nyan/CollapseLauncher/issues/27#issue-1387892275

**Comment by muscularcandy67** [comment]
Just to be sure, which version are you using?

**Comment by aliimran04** [comment]
Right now I am using this build.
https://github.com/neon-nyan/CollapseLauncher/releases/tag/CL-v1.0.52.1-fix20221019-test

**Comment by muscularcandy67** [comment]
I updated through Caches Update 4 hours ago and worked without any issue

**Comment by aliimran04** [comment]
Just now update caches works for me. Maybe the update caches issues fixed for now.

**Comment by aliimran04** [comment]
I will close the issue because the graphic issue is solved.
