### ISSUE TITLE
[Bug/Regression] Preload Check will Fail in 1.0.52 RC 1 and RC 2 Build

### ISSUE THREAD

**Issue by neon-nyan** [neon-nyan/CollapseLauncher#40]
# Describe Your Issue
The launcher will fail to check the game state if the preload is available and the launcher will keep asking you to relocate the game location and lock the launcher into this step repeatedly.
This issue is reproducible in all current 1.0.52 RC1 (minor .1) and RC2 (minor .2) builds

# Step to Reproduce
1. Open the Launcher and Select an Installed Game with Preload available.
2. The launcher will ask the user to relocate the game location.
3. The launcher keep asking the user to relocate the game location.

# Additional Info (Debug Info/Any Useful Info)
This issue was caused by the ``GameDirPath`` in ``HomePage`` not assigned to the game location path resulting null data and then ``IsPreDownloadCompleted()`` expecting non-null value and throw ``ArgumentNullException`` as a result.

![image](https://user-images.githubusercontent.com/30566970/197744700-2c4dca76-cb16-44d5-ae35-a84abf5eff85.png)

### Log:
```
[Erro]  The necessary section of Launcher Scope's config.ini is broken.
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at CollapseLauncher.Pages.HomePage.IsPreDownloadCompleted() in C:\myGit\CollapseLauncher\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 428
   at CollapseLauncher.Pages.HomePage.CheckCurrentGameState() in C:\myGit\CollapseLauncher\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 384
   at CollapseLauncher.Pages.HomePage.StartLoadedRoutine(Object sender, RoutedEventArgs e) in C:\myGit\CollapseLauncher\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 84
```

**Comment by neon-nyan** [comment]
This issue will be addressed in the next RC2 (minor .3) build.
I really recommend you to reinstall the launcher with the new build since the launcher will be locked out by the dialog box and you can't navigate to Update page

**Comment by neon-nyan** [comment]
This issue has been addressed in the latest Release Candidate build:
https://github.com/neon-nyan/CollapseLauncher/releases/tag/CL-v1.0.52.3-RC2
