### ISSUE TITLE
[Genshin Impact] [Metadata] [Preload] Metadata error is back

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#49]
![image](https://user-images.githubusercontent.com/12277635/199366222-6eb1ec68-a73b-4658-9ed2-9a275cbf8420.png)
```
System.NullReferenceException: Oops, the launcher cannot finalize the installation but don't worry, your game has been totally updated.
	Please report this issue to our GitHub here: https://github.com/neon-nyan/CollapseLauncher/issues/new or come back to the launcher and make sure to use Repair Game in Game Settings button later.
Throw: System.NullReferenceException: Object reference not set to an instance of an object.
   at CollapseLauncher.InstallManagement.BuildPersistentManifest(List`1 Entries, Dictionary`2 HashtableManifest) in D:\Repo\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 757
   at CollapseLauncher.InstallManagement.PostInstallVerification(UIElement Content) in D:\Repo\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 655
   at CollapseLauncher.InstallManagement.FinalizeInstallation(UIElement Content) in D:\Repo\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 497
   at CollapseLauncher.InstallManagement.FinalizeInstallationAsync(UIElement Content) in D:\Repo\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 1039
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in D:\Repo\CollapseLauncher\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 1368
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CollapseLauncher.InstallManagement.BuildPersistentManifest(List`1 Entries, Dictionary`2 HashtableManifest) in D:\Repo\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 757
   at CollapseLauncher.InstallManagement.PostInstallVerification(UIElement Content) in D:\Repo\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 655
   at CollapseLauncher.InstallManagement.FinalizeInstallation(UIElement Content) in D:\Repo\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 497
   at CollapseLauncher.InstallManagement.FinalizeInstallationAsync(UIElement Content) in D:\Repo\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 1039
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in D:\Repo\CollapseLauncher\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 1368
   --- End of inner exception stack trace ---
```

**Comment by neon-nyan** [comment]
I just noticed that the dispatcher keys were changed in 3.2 update.
I've just pushed the new metadata update including new dispatcher keys to fix this issue.

**Comment by Cryotechnic** [comment]
Can confirm that the metadata update fixed the error above. Thanks!
